name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      api-solid-pg:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          DATABASE_USER: docker
          DATABASE_PASS: docker
          DATABASE_HOST: localhost  # ou o IP do servidor
          DATABASE_PORT: 5432      # ou a porta do seu banco
          DATABASE_NAME: apisolid  # o nome do banco
          options: --health-cmd="pg_isready -U docker" --health-timeout=5s --health-retries=5


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U docker; do
            echo "Waiting for database to be ready..."
            sleep 5
          done

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@api-solid-pg:5432/apisolid?schema=public"